export const SURVEY_QUESTIONS = {
  "q1": "Độ tuổi của bạn",
  "q2": "Nghề nghiệp của bạn",
  "q3": "Khu vực bạn sinh sống",
  "q4": "Bạn đăng ký khảo sát này cho ai?",
  "q5": "Bạn đã từng sử dụng dịch vụ tham vấn/ trị liệu tâm lý chưa?",
  "q6": "Thông thường, khi bạn chủ động tìm kiếm sự trợ giúp tâm lý, mức độ cần thiết của bạn ở mức nào?",
  "q7": "Khi quyết định liên hệ, cảm xúc chủ đạo của bạn là gì?",
  "q8": "Điều gì khiến bạn chần chừ chưa muốn sử dụng dịch vụ tâm lý?",
  "q9": "Điều gì quan trọng nhất khi lựa chọn dịch vụ tham vấn/ trị liệu tâm lý?",
  "q10": "Bạn kỳ vọng được phản hồi sau khi đăng ký tìm hiểu dịch vụ trong bao lâu?",
  "q11": "Bạn thoải mái chia sẻ sơ bộ vấn đề của mình qua cách nào nhất TRƯỚC KHI gặp chuyên gia?",
  "q12": "Thông tin nào bạn muốn biết nhất trước khi sử dụng dịch vụ?",
  "q13": "Sau khi đăng ký, bạn kỳ vọng được sắp xếp buổi tham vấn đầu tiên trong bao lâu?",
  "q14": "Nếu phải lựa chọn, bạn ưu tiên điều nào hơn?",
  "q15": "Nếu gặp vấn đề với dịch vụ, điều gì quan trọng nhất với bạn?",
  "q16": "Khi lựa chọn chuyên gia tâm lý, điều gì quan trọng nhất với bạn?",
  "q17": "Bạn muốn được ghép chuyên gia theo cách nào?",
  "q18": "Nếu cảm thấy không phù hợp với chuyên gia đầu tiên, bạn mong muốn?",
  "q19": "Hình thức tham vấn bạn cảm thấy thoải mái nhất?",
  "q20": "Điều gì khiến bạn cảm thấy an tâm khi chia sẻ?",
  "q21": "Yếu tố nào về không gian phòng khám/ văn phòng khiến bạn an tâm nhất?",
  "q22": "Sau buổi tham vấn, bạn mong muốn nhận được gì?",
  "q23": "Bạn mong muốn được ai hỏi thăm/ theo dõi tiến độ sau buổi tham vấn?",
  "q24": "Điều gì khiến bạn quyết định sử dụng một dịch vụ hỗ trợ tâm lý?",
  "q25": "Nếu đã đăng ký nhưng sau đó bạn im lặng hoặc hủy lịch, lý do lớn nhất thường là gì?",
  "q26": "Bạn định nghĩa thế nào là một dịch vụ hỗ trợ tâm lý thành công đối với bạn?"
};